# Generated by Django 3.2.7 on 2022-08-15 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_me', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dr_reg',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user_reg',
            name='id',
        ),
        migrations.AlterField(
            model_name='dr_reg',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
