# Generated by Django 3.2.7 on 2022-08-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_me', '0002_auto_20220815_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
