# Generated by Django 3.2.7 on 2022-08-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_me', '0003_auto_20220815_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
    ]
