# Generated by Django 3.2.7 on 2022-08-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_me', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dr_reg',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
