# Generated by Django 3.2.7 on 2022-09-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_me', '0007_auto_20220904_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dr_reg',
            name='image',
            field=models.ImageField(upload_to='profile'),
        ),
    ]
